/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.claculator;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author jleeg
 */
public class JFrame extends javax.swing.JFrame {
    
    double num1 = 0, num2 = 0, result = 0;
    char operator;
    
    public void math() {
        switch(operator){
            case '+': result = num1 + num2; break;
            case '-': result = num1 - num2; break;
            case '*': result = num1 * num2; break;
            case '/': result = num1 / num2; break;
            case '%': result = num1 / 100; break;
            case '√': result = Math.sqrt(num1); break;
            case '^': result = Math.pow(num1, num2); break;
        }
        textfield.setText(String.valueOf(result));
        num1 = result;
    }

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(33,33,33));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        equButton = new javax.swing.JButton();
        jButton06 = new javax.swing.JButton();
        decButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jButton03 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton04 = new javax.swing.JButton();
        jButton05 = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        mulButton = new javax.swing.JButton();
        jButton07 = new javax.swing.JButton();
        jButton08 = new javax.swing.JButton();
        jButton09 = new javax.swing.JButton();
        clrButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        braButton = new javax.swing.JButton();
        perButton = new javax.swing.JButton();
        rootButton = new javax.swing.JButton();
        sineButton = new javax.swing.JButton();
        piButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        exButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        rootButton3 = new javax.swing.JButton();
        rootButton4 = new javax.swing.JButton();
        textfield = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(23, 23, 23));

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        equButton.setBackground(new java.awt.Color(0, 0, 204));
        equButton.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        equButton.setForeground(new java.awt.Color(255, 255, 255));
        equButton.setText("=");
        equButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equButtonActionPerformed(evt);
            }
        });

        jButton06.setBackground(new java.awt.Color(25, 37, 56));
        jButton06.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton06.setForeground(new java.awt.Color(255, 255, 255));
        jButton06.setText("6");
        jButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton06ActionPerformed(evt);
            }
        });

        decButton.setBackground(new java.awt.Color(25, 37, 56));
        decButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        decButton.setText(".");
        decButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(2, 9, 22));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jButton03.setBackground(new java.awt.Color(25, 37, 56));
        jButton03.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton03.setText("3");
        jButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton03ActionPerformed(evt);
            }
        });

        jButton0.setBackground(new java.awt.Color(25, 37, 56));
        jButton0.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton0.setForeground(new java.awt.Color(255, 255, 255));
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton02.setBackground(new java.awt.Color(25, 37, 56));
        jButton02.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton02.setForeground(new java.awt.Color(255, 255, 255));
        jButton02.setText("2");
        jButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton02ActionPerformed(evt);
            }
        });

        delButton.setBackground(new java.awt.Color(25, 37, 56));
        delButton.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        delButton.setForeground(new java.awt.Color(255, 255, 255));
        delButton.setText("DEL");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(25, 37, 56));
        jButton1.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton04.setBackground(new java.awt.Color(25, 37, 56));
        jButton04.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton04.setText("4");
        jButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton04ActionPerformed(evt);
            }
        });

        jButton05.setBackground(new java.awt.Color(25, 37, 56));
        jButton05.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton05.setForeground(new java.awt.Color(255, 255, 255));
        jButton05.setText("5");
        jButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton05ActionPerformed(evt);
            }
        });

        subButton.setBackground(new java.awt.Color(2, 9, 22));
        subButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subButton.setForeground(new java.awt.Color(255, 255, 255));
        subButton.setText("-");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        mulButton.setBackground(new java.awt.Color(2, 9, 22));
        mulButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mulButton.setForeground(new java.awt.Color(255, 255, 255));
        mulButton.setText("x");
        mulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulButtonActionPerformed(evt);
            }
        });

        jButton07.setBackground(new java.awt.Color(25, 37, 56));
        jButton07.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton07.setForeground(new java.awt.Color(255, 255, 255));
        jButton07.setText("7");
        jButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton07ActionPerformed(evt);
            }
        });

        jButton08.setBackground(new java.awt.Color(25, 37, 56));
        jButton08.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jButton08.setForeground(new java.awt.Color(255, 255, 255));
        jButton08.setText("8");
        jButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton08ActionPerformed(evt);
            }
        });

        jButton09.setBackground(new java.awt.Color(25, 37, 56));
        jButton09.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton09.setForeground(new java.awt.Color(255, 255, 255));
        jButton09.setText("9");
        jButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton09ActionPerformed(evt);
            }
        });

        clrButton.setBackground(new java.awt.Color(102, 0, 102));
        clrButton.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        clrButton.setForeground(new java.awt.Color(255, 255, 255));
        clrButton.setText("AC");
        clrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrButtonActionPerformed(evt);
            }
        });

        divButton.setBackground(new java.awt.Color(2, 9, 22));
        divButton.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        divButton.setForeground(new java.awt.Color(255, 255, 255));
        divButton.setText("/");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        braButton.setBackground(new java.awt.Color(0, 51, 51));
        braButton.setFont(new java.awt.Font("Javanese Text", 1, 10)); // NOI18N
        braButton.setForeground(new java.awt.Color(255, 255, 255));
        braButton.setText("( )");
        braButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                braButtonActionPerformed(evt);
            }
        });

        perButton.setBackground(new java.awt.Color(2, 9, 22));
        perButton.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        perButton.setForeground(new java.awt.Color(255, 255, 255));
        perButton.setText("%");
        perButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perButtonActionPerformed(evt);
            }
        });

        rootButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rootButton.setText("√");
        rootButton.setActionCommand("");
        rootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootButtonActionPerformed(evt);
            }
        });

        sineButton.setText("sin");
        sineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sineButtonActionPerformed(evt);
            }
        });

        piButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        piButton.setText(" π");
        piButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piButtonActionPerformed(evt);
            }
        });

        cosButton.setText("cos");
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });

        label.setBackground(new java.awt.Color(51, 51, 51));
        label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label.setForeground(new java.awt.Color(153, 0, 204));
        label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        exButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exButton.setText("^");
        exButton.setActionCommand("");
        exButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exButtonActionPerformed(evt);
            }
        });

        logButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        logButton.setText("log");
        logButton.setActionCommand("");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        rootButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rootButton3.setText("M");
        rootButton3.setActionCommand("");
        rootButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootButton3ActionPerformed(evt);
            }
        });

        rootButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rootButton4.setText("√");
        rootButton4.setActionCommand("");
        rootButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(exButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(rootButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(rootButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(piButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(sineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(clrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(braButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(perButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(equButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exButton)
                    .addComponent(rootButton4)
                    .addComponent(logButton)
                    .addComponent(rootButton3))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rootButton)
                    .addComponent(piButton)
                    .addComponent(sineButton)
                    .addComponent(cosButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(braButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(perButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(mulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textfield.setBackground(new java.awt.Color(204, 204, 204));
        textfield.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        textfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton06ActionPerformed
        textfield.setText(textfield.getText()+ "6");
    }//GEN-LAST:event_jButton06ActionPerformed

    private void jButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton04ActionPerformed
        textfield.setText(textfield.getText()+ "4");
    }//GEN-LAST:event_jButton04ActionPerformed

    private void jButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton05ActionPerformed
        textfield.setText(textfield.getText()+ "5");
        
    }//GEN-LAST:event_jButton05ActionPerformed

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonActionPerformed
        
        String currentText = textfield.getText();
        if (currentText.isEmpty()) {
        textfield.setText("-");}
        num1 = Double.parseDouble(textfield.getText());
        operator = '-';
        textfield.setText("");
        label.setText(num1 + "-");
    }//GEN-LAST:event_subButtonActionPerformed

    private void mulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulButtonActionPerformed
        num1 = Double.parseDouble(textfield.getText());
        operator = '*';
        textfield.setText("");
        label.setText(num1 + "*");


    }//GEN-LAST:event_mulButtonActionPerformed

    private void jButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton07ActionPerformed
        textfield.setText(textfield.getText()+ "7");
    }//GEN-LAST:event_jButton07ActionPerformed

    private void jButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton08ActionPerformed
        textfield.setText(textfield.getText()+ "8");
    }//GEN-LAST:event_jButton08ActionPerformed

    private void jButton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton09ActionPerformed
        textfield.setText(textfield.getText()+ "9");
    }//GEN-LAST:event_jButton09ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        textfield.setText(textfield.getText()+ "0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        String string = textfield.getText();
        textfield.setText("");
        for (int i = 0; i < string.length() - 1; i++) {
                textfield.setText(textfield.getText() + string.charAt(i));
            }
    }//GEN-LAST:event_delButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        textfield.setText(textfield.getText()+ "1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton03ActionPerformed
        textfield.setText(textfield.getText()+ "3");
    }//GEN-LAST:event_jButton03ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        num1 = Double.parseDouble(textfield.getText());
        textfield.setText("");
        operator = '+';
        label.setText(num1 + "+");
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void equButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equButtonActionPerformed
        num2 = Double.parseDouble(textfield.getText());
        math();
        label.setText(Double.toString(result));
        
    }//GEN-LAST:event_equButtonActionPerformed

    private void clrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrButtonActionPerformed
        textfield.setText("");
    }//GEN-LAST:event_clrButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
        num1 = Double.parseDouble(textfield.getText());
        operator = '/';
        textfield.setText("");
        label.setText(num1 + "/");
    }//GEN-LAST:event_divButtonActionPerformed

    private void braButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_braButtonActionPerformed
        textfield.setText("(");
        //num1 = Double.parseDouble(textfield.getText());
        //textfield.setText(")");
    }//GEN-LAST:event_braButtonActionPerformed

    private void perButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perButtonActionPerformed
        num1 = Double.parseDouble(textfield.getText());
        operator = '%';
        //textfield.setText("");
        label.setText(num1 + "%");
        //label.setText(Double.toString(result));
    }//GEN-LAST:event_perButtonActionPerformed

    private void textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldActionPerformed

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtonActionPerformed
        num1 = Double.parseDouble(textfield.getText());
        Math.toRadians(num1);
        textfield.setText(String.valueOf(Math.cos(num1)));
        label.setText( "cos" + num1 );
    }//GEN-LAST:event_cosButtonActionPerformed

    private void rootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootButtonActionPerformed
        //textfield.setText("√");
        num1 = Double.parseDouble(textfield.getText());
        operator = '√';
        label.setText(num1 + "√");
    }//GEN-LAST:event_rootButtonActionPerformed

    private void piButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piButtonActionPerformed

        textfield.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_piButtonActionPerformed

    private void sineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sineButtonActionPerformed
        num1 = Double.parseDouble(textfield.getText());
        Math.toRadians(num1);
        textfield.setText(String.valueOf(Math.sin(num1)));
        label.setText( "sin" + num1 );
    }//GEN-LAST:event_sineButtonActionPerformed

    private void jButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton02ActionPerformed
        textfield.setText(textfield.getText()+ "2");
    }//GEN-LAST:event_jButton02ActionPerformed

    private void decButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decButtonActionPerformed
        textfield.setText(textfield.getText().concat("."));
    }//GEN-LAST:event_decButtonActionPerformed

    private void exButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exButtonActionPerformed
        num1 = Double.parseDouble(textfield.getText());
        operator = '^';
        textfield.setText("");
        label.setText(num1 + "^");
    }//GEN-LAST:event_exButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        num1 = Double.parseDouble(textfield.getText());
        textfield.setText(String.valueOf(Math.log(num1)));
        label.setText("log10 " + num1);
    }//GEN-LAST:event_logButtonActionPerformed

    private void rootButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rootButton3ActionPerformed

    private void rootButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rootButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton braButton;
    private javax.swing.JButton clrButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton decButton;
    private javax.swing.JButton delButton;
    private javax.swing.JButton divButton;
    private javax.swing.JButton equButton;
    private javax.swing.JButton exButton;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton03;
    private javax.swing.JButton jButton04;
    private javax.swing.JButton jButton05;
    private javax.swing.JButton jButton06;
    private javax.swing.JButton jButton07;
    private javax.swing.JButton jButton08;
    private javax.swing.JButton jButton09;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JButton logButton;
    private javax.swing.JButton mulButton;
    private javax.swing.JButton perButton;
    private javax.swing.JButton piButton;
    private javax.swing.JButton rootButton;
    private javax.swing.JButton rootButton3;
    private javax.swing.JButton rootButton4;
    private javax.swing.JButton sineButton;
    private javax.swing.JButton subButton;
    private javax.swing.JTextField textfield;
    // End of variables declaration//GEN-END:variables
}
